### ISSUE TITLE
Why not px_flutter instead of mercado_pago_mobile_checkout?

### ISSUE THREAD

**Issue by ManuLpz4** [Gazer/px-flutter#1]
I think it's the perfect name :P

**Comment by Gazer** [comment]
Honestly, I think that 'px_flutter' is shorter but more difficult to discover if you do not know that the native ones are called px-something. 

Also maybe in the future, MercadoPago may want to use that name to release their own version and I do not want to argue with them about a name :).

I will add this to the FAQ thanks for the question!
