### ISSUE TITLE
Error: Algo salió mal

### ISSUE THREAD

**Issue by elespantosoterry** [Gazer/px-flutter#11]
Hola! Estuve utilizando la libreria la cual me parece espectacular, sin embargo tengo un problema y es que con cualquier preference que genere me sale el mensaje de Algo salió mal (Something went wrong).
Busque en otras Issues anteriores y vi que alguien le pasaba algo similar sin embargo fue porque puso el access token en lugar del public key. Pero yo no estoy comentiendo ese error, estoy podiendo el  Public Key y una preferencia.
La preferencia es correcta porque funciona correctamente si ingreso al enlace que me genera el json.

![image](https://user-images.githubusercontent.com/39830789/96388844-40bc7000-1171-11eb-8de8-d3652681fc83.png)

![image](https://user-images.githubusercontent.com/39830789/96388849-503bb900-1171-11eb-8eec-2a4f1139b588.png)

**Comment by elespantosoterry** [comment]
Hola! Logre después de muchos intentos logre solucionar el error. No sabia que era algo obligatorio, pero para generar la preferencia tuve que agrear un email como dato del Payer y se arregló. 

![image](https://user-images.githubusercontent.com/39830789/96637760-c0b71700-12e4-11eb-933c-452e11523adf.png)

**Comment by Gazer** [comment]
Ah, genial, lo voy a agregar en el FAQ. Pero si, el email es obligatorio y
no puede ser igual a que tenes en la cuenta de MercadoPago (o sea no te
podes pagar a vos mismo).

Tambien encontre que algunos dominios tirar error (los tipicos que se usan
para evitar spam como email temporales).
