### ISSUE TITLE
Problema con pods

### ISSUE THREAD

**Issue by vicenteign** [Gazer/px-flutter#12]
Hola! tengo el siguiente problema y no me permite compilar para IOS. Actualicé Flutter a su ultima versión y recibo el siguiente error. ¿Alguien tiene alguna solución? Gracias de antemano

 [!] CocoaPods could not find compatible versions for pod "mercado_pago_mobile_checkout":
      In Podfile:
        mercado_pago_mobile_checkout (from `.symlinks/plugins/mercado_pago_mobile_checkout/ios`)

    Specs satisfying the `mercado_pago_mobile_checkout (from `.symlinks/plugins/mercado_pago_mobile_checkout/ios`)` dependency were found, but they
    required a higher minimum deployment target.

**Comment by unacorbatanegra** [comment]
Hola!, mismo problema en Flutter stable v1.22.5

**Comment by Gazer** [comment]
Esta semana trato de ver. Por las dudas, que versión de xcode están tienen
instalado? Están usando Big Sur?

**Comment by unacorbatanegra** [comment]
Gracias!, Xcode 12.0, Big Sur 11.0.1

**Comment by vicenteign** [comment]
Gracias!! Xcode version 12.3, Big Sur 11.1

**Comment by BrunoLeonardoRamosRibeiro** [comment]
El mismo problema está sucediendo también con Catalina 10.15.7 y XCode 12.3.

**Comment by cassianogr** [comment]
I have the same problem too.

**Comment by vicenteign** [comment]
Hola @Gazer! consulta, pudiste ver que está originando el problema con el paquete? Gracias de antemano.

**Comment by lucasrueda** [comment]
![image](https://user-images.githubusercontent.com/24287521/103412060-1fed9f00-4b52-11eb-9fe9-c56a64d3c66e.png)

El SDK nativo de MercadoPago necesita que el target del proyecto sea iOS 10.0+

Flutter por defecto pone target 8.0... simplemente cambienlo a 10.0 y les tiene que andar.

**Comment by vicenteign** [comment]
Hola @lucasrueda Gracias por la solución, me puedes indicar en que altura se encuentra el archivo que hay que modificar para que funcione el paquete? saludos!

**Comment by lucasrueda** [comment]
Sii @vicenteign 

Los pasos en un proyecto recien comenzado serian:

1. agregar dependencia 'mercado_pago_mobile_checkout' al pubspec.yaml
2. correr 'flutter pub get'
3. Editar el archivo ios/Podfile descomentando la segunda linea que dice:
```
# platform :ios, '9.0'
```
Tiene que quedar:
```
platform :ios, '10.0'
```

En un proyecto ya iniciado, 'flutter clean' y al paso 2

**Comment by Gazer** [comment]
Genial Lucas, muchas gracias. También estaba medio perdido, iOS no es mi
fuerte :)

Si confirman cierro el ticket y agrego algo en el FAQ/README

**Comment by vicenteign** [comment]
@Gazer Podrías modificar esa linea del paquete y subir una versión? para mantener el paquete actualizado en el pusbec.yaml.    🙏🏻 Gracias!

**Comment by vicenteign** [comment]
@lucasrueda Seguí los pasos, pero sigue apareciendo el mismo error ): A alguien le funcionó?

**Comment by lucasrueda** [comment]
A mi me aparece otro error, pero es para otro ticket

**Comment by vicenteign** [comment]
Te sale lo siguiente?
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A mercado_pago_mobile_checkout

**Comment by lucasrueda** [comment]
> Te sale lo siguiente?
> CocoaPods' output:
> ↳
> Preparing
> Analyzing dependencies
> Inspecting targets to integrate
> Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
> Finding Podfile changes
> A mercado_pago_mobile_checkout

No..

Intenta con un nuevo proyecto
```
flutter create new-project
```
Editar pubspec.yaml y agregar la dependencia mercado_pago_mobile_checkout
```
flutter pub get
```
Editar ios/Podfile y setear version 10.0
Luego abri un emulador de iOS
```
flutter run
```

Y fijate que te dice. A mi me esta dando el siguiente problema:

```
Installing mercado_pago_mobile_checkout
- Running pre install hooks
 [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLCardForm)
```

Cuando creo un proyecto con xCode (totalmente nativo) y agrego la dependencia MercadoPagoSDK me pasa exactamente lo mismo, asi que el problema no tiene que ver con este plugin de flutter sino con el repo oficial de MercadoPagoSDK para iOS mas alguna actualizacion de Flutter. Todavia no lo resuelvo.

Pero el problema que te dio a vos @vicenteign con el que iniciaste este ticket ya se soluciona cambiando el Podfile y seteando version 10.0

**Comment by unacorbatanegra** [comment]
Mismo problema del de arriba

**Comment by BrunoLeonardoRamosRibeiro** [comment]
Ya había probado las soluciones anteriores.
Pero no funcionaron.

**Comment by Gazer** [comment]
Ahí hice un par de pruebas y tanto la app en la carpeta example como una nueva cambiando en el Podfile el platform a `platform :ios, '10.0'` me compilan y corren sin problemas.

El valor por defecto como dijo @lucasrueda en Flutter hay que cambiarlo pero no puedo hacerlo desde el plugin porque es un archivo generado en la carpeta de la applicación (`ios/Podfile`)

**Comment by lucasrueda** [comment]
@Gazer qué versión de Xcode tenés?

**Comment by Gazer** [comment]
12.3 con Big Sur

**Comment by vicenteign** [comment]
@lucasrueda Tienes razón, me sale el error: 
Installing mercado_pago_mobile_checkout
- Running pre install hooks
 [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLCardForm).

**Comment by lautaropaske** [comment]
Yo tengo los mismos problemas que @vicenteign y @lucasrueda pero me anduvo la app de ejemplo del repositorio, como comenta @Gazer

**Comment by lautaropaske** [comment]
¿@Gazer podrías pasarnos tu `flutter doctor -v`?

**Comment by Gazer** [comment]
Ahora lo pude reproducir. Por lo que veo es algo general, este [reporte](https://github.com/flutter/flutter/issues/58584) en el repo de Flutter esta open todavia aunque no termine de leerlo.

```
➜  px_test flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-AR)
    • Flutter version 1.22.5 at /Users/gazer/fvm/versions/stable
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gazer/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • D22F23F2-58B0-49A7-910A-616823ABA0A8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

```

**Comment by Gazer** [comment]
```
    -> Installing mercado_pago_mobile_checkout (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLCardForm)
```

Este error me hace ruido, no se porque dice 0.0.1 si en el pubspec tengo 0.0.2.

**Comment by lautaropaske** [comment]
El 0.0.1 viene de `mercado_pago_mobile_checkout.podspec`:
```
 Pod::Spec.new do |s|
  s.name             = 'mercado_pago_mobile_checkout'
  s.version          = '0.0.1'
```

Entiendo que es el archivo que define la metadata del Pod que genera el package

**Comment by lautaropaske** [comment]
> Ahora lo pude reproducir. Por lo que veo es algo general, este [reporte](https://github.com/flutter/flutter/issues/58584) en el repo de Flutter esta open todavia aunque no termine de leerlo.
> 
> flutter doctor -v

El error es el mismo pero hace referencia a un archivo específico de Flutter. Igual, probé pasarme a la versión de Flutter que tiene el fix que se sugiere en ese reporte pero sigo teniendo el mismo problema con `MLCardForm`.

**Comment by lucasrueda** [comment]
Sii el problema esta en el repo de MercadoPago.

Logre hacerlo andar en un proyecto nuevo nativo haciendo lo siguiente:

1. Iniciar un proyecto nativo con XCode
2. Descargar el repo de MercadoPago y ubicarlo en una carpeta ( le puse **melisdk** )
3. Correr ``` pod init ```
4. Modificar los archivos **Podfile** y **melisdk/MercadoPagoSDK.podspec*** de las siguientes maneras:

**Podfile**

```
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

plugin 'cocoapods-clean_build_phases_scripts'

target 'meli' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meli

  pod 'MercadoPagoSDK', :path => './melisdk/'
  pod 'AndesUI/AndesBottomSheet', '3.17'

end
```
La clave aqui es utilizar el MercadoPagoSDK desde el path determinado y usar esa version de AndesBottomSheet porque se rompe con la 3.18

**./melisdk/MercadoPagoSDK.podspec**

```
Pod::Spec.new do |s|
  s.name             = "MercadoPagoSDK"
  s.version          = "4.32.4"
  s.summary          = "MercadoPagoSDK"
  s.homepage         = "https://www.mercadopago.com"
  s.license          = { :type => "MIT", :file => "LICENSE" }
  s.author           = "Mercado Pago"
  s.source           = { :git => "https://github.com/mercadopago/px-ios.git", :tag => s.version.to_s }
  s.swift_version = '4.2'
  s.platform     = :ios, '10.0'
  s.requires_arc = true
  s.default_subspec = 'Default'
  s.static_framework = true

  s.subspec 'Default' do |default|
    default.source_files = ['MercadoPagoSDK/MercadoPagoSDK/**/**/**.{h,m,swift}']
    default.resources = ['MercadoPagoSDK/Resources/**/*.xib']
    default.resource_bundles = {
      'MercadoPagoSDKResources' => [
        'MercadoPagoSDK/Resources/**/*.xcassets',
        'MercadoPagoSDK/Resources/**/*.{lproj,strings,stringsdict}',
        'MercadoPagoSDK/Resources/**/*.plist'
      ]
    }
    default.dependency 'MLUI'
    default.dependency 'MLCardDrawer'
    s.dependency 'MLBusinessComponents'
    s.dependency 'MLCardForm'
    s.dependency 'AndesUI/AndesBottomSheet'
  end

  #s.test_spec do |test_spec|
    #test_spec.source_files = 'MercadoPagoSDK/MercadoPagoSDKTests/*'
    #test_spec.frameworks = 'XCTest'
  #end

end
```

La clave de este podspec de MercadoPagoSDK es habilitar la línea ```  s.static_framework = true ``` y quitar las versiones de sus dependencias, ya que esas dependencias viejas no tienen la linea ``` s.static_framework = true ``` activada

Una foto de la estructura del proyecto

![image](https://user-images.githubusercontent.com/24287521/103819515-5727e880-5049-11eb-9243-d42207d829a4.png)



Con estos pasos logre levantar el proyecto sin que falle el tema de ```has transitive dependencies that include statically linked binaries```

Me falla de todos modos a la hora de intentar el checkout con una preferenceId y una publicKey determinadas

**Comment by lautaropaske** [comment]
Impecable @lucasrueda. Calculo que esto valida que el problema viene por el lado de `px-ios`. Estaría buenísimo entrar en contacto con ellos y tener un ETA del nuevo release. El último público fue 3.32.4 en Feb 2020 y desde entonces se avanzó bastante.

**Comment by vicenteign** [comment]
Hola chicos, Por casualidad alguien ha recibido alguna respuesta de que es lo que ocurre con el paquete?

**Comment by unacorbatanegra** [comment]
Lee el commit que referenciaron, en mi caso, hice lo siguiente:
* clone el proyecto y lo referencie con el path:

![image](https://user-images.githubusercontent.com/44511181/104918874-2bbfca80-5974-11eb-89be-21fc0231db81.png)

* modifique como lo hizo @lautaropaske  en su pr:
![image](https://user-images.githubusercontent.com/44511181/104918951-4abe5c80-5974-11eb-943c-f44667b8305a.png)
y listo, funciono perfecto, te puede servir hasta que se acepte el pr y saquen release.
Gracias @lautaropaske  por la solucion.

**Comment by vicenteign** [comment]
Gracias @unacorbatanegra 
Intenté hacer lo mismo que tu y después de un par de errores me sale lo siguiente.
¿Alguien sabe que puede ser?

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Flutter
      - mercado_pago_mobile_checkout
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `mercado_pago_mobile_checkout` from `.symlinks/plugins/mercado_pago_mobile_checkout/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_3_5.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/6/3/5/MercadoPagoSDK/4.32.4/MercadoPagoSDK.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_3_3_8.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/3/8/MLCardForm/0.9.3/MLCardForm.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/d/c/MLCardDrawer/1.5.2/MLCardDrawer.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "MLCardForm":
      In snapshot (Podfile.lock):
        MLCardForm (= 0.8.2, ~> 0.1)
      In Podfile:
        mercado_pago_mobile_checkout (from `.symlinks/plugins/mercado_pago_mobile_checkout/ios`) was resolved to 0.0.1, which depends on
          MLCardForm (= 0.9.1)
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `MLCardForm` inside your development pod `mercado_pago_mobile_checkout`.
       You should run `pod update MLCardForm` to apply changes you've made.
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 12 Pro Max.
Exited (sigterm)

**Comment by Gazer** [comment]
Te lo dice al final. ` pod repo update`

**Comment by vicenteign** [comment]
Si, luego lo noté y se arregló. Gracias @Gazer

**Comment by unacorbatanegra** [comment]
Con respecto a la solución anterior.
Corriendo la app en modo debug funciona super bien:
![image](https://user-images.githubusercontent.com/44511181/105077249-fd70e680-5a6a-11eb-9071-7020729748b8.png)

Sin embargo, al tratar de hacer un build:
![image](https://user-images.githubusercontent.com/44511181/105077541-6bb5a900-5a6b-11eb-87f4-40a7f1392c3a.png)

No encontré doc que me ayude con el tema :(

**Comment by vicenteign** [comment]
unacorbatanegra Hola! ¿Donde referenciaste el path?  yo no pude hacerlo pero lo hice referenciando la url de git y no funciona bien. Me podrías explicar dónde dejaste alojado y qué carpeta fue la que necesitaste para agregar el "../px-flutter" ¿Es el proyecto entero? ó solo una carpeta de ios? Te agradecería un montón

**Comment by vicenteign** [comment]
Hola! Hice lo que dijo @unacorbatanegra  pero al intentar pasar a la ventana de mercadopago me sale el siguiente error y se cae el emulador 
![image](https://user-images.githubusercontent.com/12106308/105748301-b67a6980-5f20-11eb-91e0-4c94f4b7082a.png)

**Comment by unacorbatanegra** [comment]
Hola @vicenteign , te falta implementar correctamente lo que aparece en el readme del repositorio, dale una revisada.

**Comment by vicenteign** [comment]
Gracias @unacorbatanegra  voy a revisar

**Comment by Gazer** [comment]
Ya hice el release de la versión 0.0.3 que debería arreglar este problema. Si alguien sigue con problemas despue de esto vemos que otra cosa puede ser.

**Comment by EduardoHidalgo** [comment]
Negativo 13:14, usando la versión 0.0.3 me arroja el siguiente error: 

> [!] Error installing MLCardDrawer
> [!] /opt/homebrew/bin/git clone https://github.com/mercadolibre/meli-card-drawer-ios.git /var/folders/_r/j69s_yrn5xvgr3ccgc69xt1w0000gn/T/d20210219-4365-1nftk0o --template= --single-branch --depth 1 --branch 1.5.1
> 
> Cloning into '/var/folders/_r/j69s_yrn5xvgr3ccgc69xt1w0000gn/T/d20210219-4365-1nftk0o'...

**Comment by ncalderini** [comment]
@Gazer Tengo un problema similar pero ahora con la version `0.1.0` de la lib, 

```The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLBusinessComponents)```

Me pasa incluso en un proyecto recién creado con `flutter create` y agregando la dependencia.

**Comment by confiraloterias** [comment]
> @Gazer Tengo un problema similar pero ahora con la version `0.1.0` de la lib,
> 
> `The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLBusinessComponents)`
> 
> Me pasa incluso en un proyecto recién creado con `flutter create` y agregando la dependencia.
> 
> Mi flutter doctor:
> 
> ```
> [✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-AR)
>     • Flutter version 2.0.6 at /Users/ncalderini/Library/flutter
>     • Framework revision 1d9032c7e1 (8 days ago), 2021-04-29 17:37:58 -0700
>     • Engine revision 05e680e202
>     • Dart version 2.12.3
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/ncalderini/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5, Build version 12E262
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> 
> [✓] VS Code (version 1.56.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.22.0
> 
> [✓] Connected device (2 available)
>     • iPhone 11 Pro Max (mobile) • 97AED146-699D-4F2C-B1A3-BCB3EF072C7D • ios            •
>       com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
>     • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93
> ```
Hi ncalderini, did you solve this problem?

**Comment by ncalderini** [comment]
@confiraloterias Hi, yes I modified the `mercado_pago_mobile_checkout.podspec` podfile, you need to add this line 
`s.dependency 'MLBusinessComponents', '1.29.0'`

You can modify this file by creating your own fork of the lib or under the path `yourProject/ios/.symlinks/plugins/mercado_pago_mobile_checkout/ios/mercado_pago_mobile_checkout.podspec` although changes there will be lost if you clean and reinstall the pods.

I will create a PR with the change and hopefully it will be fixed in the next release.

**Comment by EduardoHidalgo** [comment]
@ncalderini I can confirm that this solve the error "The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLBusinessComponents)" mentioned by @confiraloterias 

I changed directly the line code that you mentioned, in ios/.symlinks/ios/mercado.pago_mobile_checkout.podspec under the dependencies already has this file. Ran "pod install" again (without clean or anything else) and compiled successfully!

For me this is enough to continue deploying my app (productive on apple store in this moment) so... ❤️ you are an angel.

Waiting for the official next release.

**Comment by sernocturno** [comment]
> @confiraloterias Hi, yes I modified the `mercado_pago_mobile_checkout.podspec` podfile, you need to add this line `s.dependency 'MLBusinessComponents', '1.29.0'`
> 
> You can modify this file by creating your own fork of the lib or under the path `yourProject/ios/.symlinks/plugins/mercado_pago_mobile_checkout/ios/mercado_pago_mobile_checkout.podspec` although changes there will be lost if you clean and reinstall the pods.
> 
> I will create a PR with the change and hopefully it will be fixed in the next release.

it works for me

**Comment by victormeloque** [comment]
> @confiraloterias Hi, yes I modified the `mercado_pago_mobile_checkout.podspec` podfile, you need to add this line `s.dependency 'MLBusinessComponents', '1.29.0'`
> 
> You can modify this file by creating your own fork of the lib or under the path `yourProject/ios/.symlinks/plugins/mercado_pago_mobile_checkout/ios/mercado_pago_mobile_checkout.podspec` although changes there will be lost if you clean and reinstall the pods.
> 
> I will create a PR with the change and hopefully it will be fixed in the next release.

This worked for me. Thanks.
