### ISSUE TITLE
Select standard payment methods

### ISSUE THREAD

**Issue by lscavalcante** [Gazer/px-flutter#16]
Hi, I would like to know if there is a possibility to limit the means of payment only for credit and debit cards?

**Comment by Gazer** [comment]
Yes, you can do it when you create the preferenceId on the server. You can
check on the "Personalización - Mobile Checkout - Mercado Pago Developers"
https://www.mercadopago.com.ar/developers/es/guides/online-payments/mobile-checkout/personalization
for more details about how to do it.
