### ISSUE TITLE
Assinatura

### ISSUE THREAD

**Issue by GUSTAVOALVESFERNANDES** [Gazer/px-flutter#18]
Oi Ricardo Markiewicz tudo bem, gostei muito do package, nesse checkout não tem com cobra por assinatura, tem como vc implementar?

**Comment by Gazer** [comment]
Não, o checkout do MercadoPago não suporta assinatura. Você deve usar a API diretamente.

(Google translated from: No, el checkout de MercadoPago no soporta suscripción. Deberías usar el API directamente.)
