### ISSUE TITLE
Soporte null-safety

### ISSUE THREAD

**Issue by ncalderini** [Gazer/px-flutter#19]
Buenas, antes que nada muchas gracias por este aporte!

Hay alguna posibilidad de darle soporte a la lib para que corra con `null-safety`? Actualmente en mi proyecto falla la compilación porque también dependo de `json_annotation` pero en la version 4.0.1 con null-safety.

Gracias

**Comment by Gazer** [comment]
Ya hice el merge de un PR que me compartieron, me falta hacer el release que seráe en breve.

**Comment by ncalderini** [comment]
Closed by #20
