### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by MaichiLydia** [Gazer/px-flutter#21]
Hi, thank you so much for this project.
Is there a way to set the language to Portuguese or translate the labels in some way?

**Comment by rodrigopequeno** [comment]
Hi @MaichiLydia,
I was looking for exactly that, and I remembered that probably the paid market sdk uses the language of the device, and that is exactly what happens.

**Comment by MaichiLydia** [comment]
Oh thanks @rodrigopequeno for the observation. Do you know if there is a way to set a single language despite of the device language ?

**Comment by rodrigopequeno** [comment]
@MaichiLydia just looking deeply into the Mercado Livre SDK to confirm but I believe he doesn't have that option.

**Comment by MaichiLydia** [comment]
Thanks for the answers
