### ISSUE TITLE
CastError

### ISSUE THREAD

**Issue by facubarberis** [Gazer/px-flutter#24]
Hola Ricardo! Antes que nada muchas gracias por el enorme aporte de esta librería.  Estoy teniendo un problema en la función startCheckout, si pudieras ayudarme te lo agradecería. Estoy en el la versión 2.2.2 de Flutter
![Issue](https://user-images.githubusercontent.com/11363555/123258859-3dc90a80-d4ca-11eb-98d9-e14d4dba8ecf.PNG)

**Comment by lleandroo93** [comment]
Same here.
Starting using this package today and this is the first error.
Using `mercado_pago_mobile_checkout: ^0.1.0` and `Flutter (Channel stable, 2.2.1)`

**Comment by Gazer** [comment]
Should be fixed on v0.1.1
