### ISSUE TITLE
!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (MLBusinessComponents)

### ISSUE THREAD

**Issue by alphonicSarita** [Gazer/px-flutter#28]
MLBusinessComponent (1.30.0)
Not working in Flutter project. Tried with new project too.
Not able to complete pod installation.

**Comment by BDJ-Corporation** [comment]
Take a look on #12 closed issue.

**Comment by alphonicSarita** [comment]
@BDJ-Corporation 
Thanks, Its working Now
