### ISSUE TITLE
CastError en startCheckout en null safety

### ISSUE THREAD

**Issue by chmereles** [Gazer/px-flutter#29]
Al ejecutar startCheckout, sale un error de tipos :
_CastError (type 'Future<Map<String, dynamic>?>' is not a subtype of type 'Future<Map<String, dynamic>>' in type cast)

pienso que así se podría solucionar:

  static Future<PaymentResult> startCheckoutEx(
    String publicKey,
    String preferenceId,
  ) async {
    Map<String, dynamic>? result =
        await (_channel.invokeMapMethod<String, dynamic>(
      'startCheckout',
      {
        "publicKey": publicKey,
        "preferenceId": preferenceId,
      },
    ));
    return PaymentResult.fromJson(result!);
  }

**Comment by ramonpaolo** [comment]
Same error here

**Comment by Gazer** [comment]
Fixed in v0.1.1
