### ISSUE TITLE
como instalar la libreria?

### ISSUE THREAD

**Issue by danielito-1** [Gazer/px-flutter#3]
disculpa mi ignorancia .

porque te hago esta pregunta?
bueno esque yo recien compre una aplicacion prediseñada y los pagos que vienen como nativos no estan activos para mi pais. me di cuenta demasiiado tarde..

**la aplicacion que compre fue esta:**

https://inspireui.com/products/fluxstore-pro/

soy de colombia

masomenos asi son las librerias ya todo viene preparado

![app](https://user-images.githubusercontent.com/63943871/81485668-89601c80-9214-11ea-93a5-2163357f7365.jpg)

por lo tanto si no se ingresar correctamente la libreria tendre errores. puedes ayudarme?

**Comment by Gazer** [comment]
Lamentablemente no, no es trivial lo que preguntas y seguramente necesites de un desarrollador que revise el codigo de la app que compraste e implemente toda la logica necesaria tanto en la app como en el backend.
