### ISSUE TITLE
Error while trying to run package example

### ISSUE THREAD

**Issue by milodude** [Gazer/px-flutter#33]
While trying to make a simple checkout with a manual generated preferenceId from the example that comes with it, I'm getting a missing a plugin error.

When initializing the example app
`Error: MissingPluginException(No implementation found for method getPlatformVersion on channel mercado_pago_mobile_checkout)`

When clicking on the "Pagar" button
`Error: MissingPluginException(No implementation found for method startCheckout on channel mercado_pago_mobile_checkout)`

I  completed the preferenceId and publicKey variables manually and run the app.

**Comment by Gazer** [comment]
You need to stop/start the app after install the plugin, is this the case? MissingPluginException is throw when you want to use a native plugin that was not compiled with the app.

**Comment by milodude** [comment]
Steps I  did.

1-Downloaded the repo again, just in case
2- Went to example folder
3-Run "flutter run -d chrome"

Did a  flutter clean and a flutter run-d chrome again just in case.

![image](https://user-images.githubusercontent.com/4110660/132710579-73dc7dda-21bd-4853-be76-d66430f21b71.png)

Am I missing something?

**Comment by Gazer** [comment]
Oh, this plugin only support Android and iOS, it does not work on web. I will close this issue.
