### ISSUE TITLE
Save the payment response into your database.

### ISSUE THREAD

**Issue by matiazar** [Gazer/px-flutter#39]
Hola! como estas @Gazer ?
queria consultarte algo.. asi no me pongo a implementar y dsp al final me doy cuenta que algo me falta.

una vez que el usuario hace el pago, o se lo rechazan o cancela, lo que sea... que sucede?
como hago ese paso que figura en la documentacion? a donde se envia el response? a mi app? a mi backend? como ? 

muchas gracias !!

**Comment by matiazar** [comment]
ahi encontre esta info
https://www.mercadopago.com.ar/developers/es/guides/online-payments/mobile-checkout/introduction

4. Enterate del pago escuchando las notificaciones que te enviamos.

pero no da mas info.

**Comment by matiazar** [comment]
disculpa que moleste nuevamente. hice el proceso de prueba. puse una url de retorno, y me trae esta info despues de hacer el pago, pero no la entiendo

como lo relaciono con mi usuario? el id o el data_id de donde salen? 
alguien me podra ayudar?
ademas en la documentacion dice que debe devolver el estado del pago 
https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-pro/test-integration
APRO = APROBADO. eso no aparece en ningun lado!

{"action":"payment.created","api_version":"v1","data":{"id":"1245008347"},"date_created":"2021-12-27T21:09:47Z","id":100499874493,"live_mode":false,"type":"payment","user_id":"232323","data_id":"1245008347"}

gracias por la ayuda

**Comment by Gazer** [comment]
No recuerdo ahora y no estoy en la compu, pero creo que con esa respuesta
podes consultar por id en la api de payments. Esto escapa un poco al
plugin, tendrías que ver bien los ejemplos de la parte de callback en
servidores.

https://www.mercadopago.com.co/developers/es/guides/manage-account/account/retrieving-payments

**Comment by matiazar** [comment]
muchas gracias x la ayuda

**Comment by Gazer** [comment]
Acá tenés el ejemplo de cómo manejar las IPN de pagos: https://www.mercadopago.com.ar/developers/es/guides/notifications/ipn
