### ISSUE TITLE
minSDK 21

### ISSUE THREAD

**Issue by ingsoto83** [Gazer/px-flutter#4]
Hola el minSdk que pide es la 21 pero en la librería oficial de px-android es 16, como puedo cambiar eso?

**Comment by Gazer** [comment]
Esta semana tengo que sacar una nueva release que baja el sdkMinVersion que quedo en 21 en la lib, si estas muy apurado podes forkear y en el pubspec.yml referenciar tu propio repo con el fix del sdkMinVersion y cuando salga publicada la versión usarla.

**Comment by ingsoto83** [comment]
Muchas gracias, si lo haré en el fork por lo pronto
