### ISSUE TITLE
Error compiling px-flutter

### ISSUE THREAD

**Issue by jesusdanielx15** [Gazer/px-flutter#40]
Im having errors runing my flutter app because of the following errors:

 > Could not resolve com.mercadopago.android.px:checkout:4.46.+. 
> Unable to load Maven meta-data from https://jcenter.bintray.com/com/mercadopago/android/px/checkout/maven-metadata.xml.
> Could not HEAD 'https://jcenter.bintray.com/com/mercadopago/android/px/checkout/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

it seems that bintray is down, is there any alternative to this? how can we make it to work?

**Comment by matiazar** [comment]
aca tambien! mismo error.. hace un par de dias funcionaba

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseAssets'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.mercadopago.android.px:checkout:4.46.+.
     Required by:
         project :app > project :mercado_pago_mobile_checkout
      > Failed to list versions for com.mercadopago.android.px:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/mercadopago/android/px/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/mercadopago/android/px/checkout/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by ValeraLetun** [comment]
JCenter deprecated

https://stackoverflow.com/questions/66651640/jcenter-deprecation-impact-on-gradle-and-android

Please replace

jcenter()

with this:

mavenCentral()

in file android\build.gradle

After February 1st, 2022 jcenter() will not work anymore.

**Comment by Gazer** [comment]
Fixed in 0.2.0-dev.1
