### ISSUE TITLE
Simple Detalle en el idioma español

### ISSUE THREAD

**Issue by ginidaniel** [Gazer/px-flutter#42]
El español hasta ahora muy bien pero dice 'New Card' -> 'New Debit Card' / 'New Credit Card' y "Cash Payment"

El resto se encuentra en español, por lo menos las pantallas que pude ver. Quizás es algo simple para agregar en una próxima versión y mejoraría la experiencia del usuario.

Gracias

**Comment by brunoalod** [comment]
Creo que eso es tema de la librería oficial de MercadoPago.

**Comment by Gazer** [comment]
@ginidaniel gracias, como dice @brunoalod esas pantallas son del proyecto px-ios de MercadoPago, no tengo control sobre eso, quizás toma el idioma del dispositivo y este está en inglés?
