### ISSUE TITLE
Problemas con el Could not resolve com.mercadopago.android.px:checkout:4.46.+

### ISSUE THREAD

**Issue by Lautaro124** [Gazer/px-flutter#43]
Hola ¿Como están?
Estoy teniendo problema con el tema de la implementación y me tira este error.
![image](https://user-images.githubusercontent.com/59624470/151414237-015e48ed-998b-41df-b8c8-1287c502f91b.png)
¿Como podría solucionarlo?

**Comment by prodriguez96** [comment]
pudiste resolverlo? tengo el mismo problema :(

**Comment by Lautaro124** [comment]
No :,C

**Comment by Lautaro124** [comment]
Si por?

**Comment by prodriguez96** [comment]
Bien, yo despues de 1 mes lo pude solucionar, yo tambien tengo la libreria de image_picker, en el build.gradle de la lib, esta seccion: 
`rootProject.allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}`

lo que tenes que hacer es borrar la parte de `maven {
            url 'https://google.bintray.com/exoplayer/'
        }`

al parecer me causaba conflictos al querer bajar la dependecia de mercado pago, fijate si te funciona

**Comment by JulianRodelo11** [comment]
Amigo me sirvió tu solución, de verdad muchas gracias por el aporte.

**Comment by prodriguez96** [comment]
me alegro mucho que te sirviera :)

**Comment by Lautaro124** [comment]
se me soluciono muchas gracias.
