### ISSUE TITLE
Lanza error al hacer checkout

### ISSUE THREAD

**Issue by AbelTarazona** [Gazer/px-flutter#48]
Todo funcionaba bien y de un momento a otro dejó de funcionar mostrando este mensaje. 
![Captura](https://user-images.githubusercontent.com/12468902/171192252-8c6c7ec5-e565-40e1-a534-23500ee9d0aa.PNG)

**Comment by dgadduci** [comment]
Tengo el mismo problema, o inclusive llega a pasar esto, pero cuando selecciono las cuotas (por ej. 1 solo pago), termina rechazando la operacion. Es aleatorio, la mayoria de las veces lo rechaza, pero en una o dos oportunidades aprobo la operacion. Pudiste solucionarlo?

**Comment by AbelTarazona** [comment]
Revisaste que estás usando las credenciales pertinentes para cada caso, quizá lo corres en DEV con key de producción

**Comment by dgadduci** [comment]
hola Abel, muchas gracias por responder. Estoy utilizando la key de prueba y el comprador un mail xxxx@testuser.com

**Comment by Gazer** [comment]
No uses el email que te muestra en la documentación cuando crees el Preference, usa un email verdadero que no sea el email de la cuenta de Mercado Pago (ya que tampoco podes pagarte a vos mismo). En mi experiencia los emails que aparecen en la documentación siempre terminan fallando de alguna manera.

**Comment by dgadduci** [comment]
Hola Gazer, antes que nada gracias por el laburo que hiciste, es impresionante. Tendras un link para ver la documentacion de mobile checkout, porque sinceramente o no se buscar o lo que encuentro en MP es muy basico, para no decir inexistente.

**Comment by Gazer** [comment]
Lamentablemente la documentación oficial de checkout es poca o inexistente.
No hay lucho más que los readme de los proyectos px-android y px-ios y
algún link que puedas encontrar ahí.

Lo que si te puedo decir que el 80% de las cosas se manejan a través del
preference (tipos de pagos, cuotas, callbacks, etc) y la UI es muy limitada
en que podes cambiar.

Para los parámetros del preference si hay un poco más de información:
https://www.mercadopago.com.ar/developers/es/reference/preferences/_checkout_preferences/post
-- 
Ing. Ricardo Markiewicz
http://www.p39.com.ar/

**Comment by dgadduci** [comment]
Muchisimas gracias por tu pronta respuesta. Te hago una ultima pregunta ya que lo que explicas en el video es clarisimo, en cuanto al tema del listener (de hecho en la aplicacion de pedidos que estoy desarrollando venia trabajando de esa forma, ya que los uso, para seguir el estado de los pedidos en tiempo real y para lo que es mensajeria entre el comercio y los clientes). 
Las pruebas de mobile checkout las hago de la siguiente forma:
1. Cree una integracion en mi cuenta de desarrollador (no una cuenta de prueba, sino la mia)
2. Luego en esa cuenta cree un usuario de prueba
3. Entro a la cuenta de prueba desde un navegador anonimo y de ahi obtengo el mail del usuario de prueba
4. hago la llamada curl y paso como parametros el access token de mi cuenta real de desarrolador (que es donde tengo declarada la integracion) y en payer el mail del usuario de la cuenta de prueba
Son correctos esos pasos? o tendria que crear otro usuario "vendedor", dentro de este crear la integracion, y cuando hago el CURL pasar el token de ese vendedor de prueba?
No se si se entendio, y disculpa por lo largo del mensaje

**Comment by MervinDiazLugo** [comment]
Dejo por aca esto que me paso, yo en el parametro currency ID estaba pasando $ , me fui a revisar la docu y estas son las monedas.

**currency_id**
_String_
ID único para identificar la moneda. Código ISO_4217. Algunos sitios permiten la moneda local y USD, pero es importante tener en cuenta que el monto se convierte a moneda local cuando se crea la preferencia, ya que el checkout siempre procesa las transacciones en moneda local. Si usas USD, ten en cuenta que este valor no se actualiza automáticamente si el valor de la moneda local cambia en relación a USD.
ARS: Argentine peso.
BRL: Brazilian real.
CLP: Chilean peso.
MXN: Mexican peso.
COP: Colombian peso.
PEN: Peruvian sol.
UYU: Uruguayan peso.


al cambiar eso en al acto se me arreglo la app

![image](https://user-images.githubusercontent.com/13653183/218326891-85117c20-7c68-46b7-91e2-3617988150b9.png)
![image](https://user-images.githubusercontent.com/13653183/218326904-86cbacd5-1cca-4730-97a4-c0144328291b.png)
