### ISSUE TITLE
No Payment Callback

### ISSUE THREAD

**Issue by wesleytoshio** [Gazer/px-flutter#49]
I have a problem with payment but I cannot identify the error that is occurring because it is not visible
![image](https://user-images.githubusercontent.com/7057737/171470253-8422fb92-0e03-4fa9-b400-d8e060298c52.png)

**Comment by dgadduci** [comment]
I have the same problem. were you able to solve it?

**Comment by gustav984** [comment]
check that the email used to create the preferenceId is not the same as the used to create the MarcadoPago account

**Comment by Gazer** [comment]
I do not know why ML libraries does not show the error. As the other comment says, the most common reason for that red alert is that the email is invalid in the preference. You can report to px-android or px-ios if need more information, there is not much I can do from the flutter plugin
