### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by andre-ab** [Gazer/px-flutter#53]
Possibility of implementation in flutter web?

**Comment by Gazer** [comment]
No, ML does not provide a checkout library for web.

**Comment by andre-ab** [comment]
Look.
https://www.mercadopago.com.br/developers/pt/docs/checkout-api/integration-configuration/card/integrate-via-cardform?fbclid=IwAR2uHzQHf31FlLAkhL0nX42inoAv_NY5KWmrijpCF8Elq26kDUTlbFxe5aY#editor_6
