### ISSUE TITLE
The com.mercadopago.android.px:services 4.46.4 SDK collects personal or sensitive data

### ISSUE THREAD

**Issue by wesleytoshio** [Gazer/px-flutter#54]
**Does anyone know of a solution to this problem?**
![image](https://user-images.githubusercontent.com/7057737/193360968-29aabd83-400a-4a05-a467-002f8ea69ba5.png)

**Comment by Gazer** [comment]
I’m working on this. I’ve a commit but I need to test it. Hopefully this
week I will do the release.
-- 
Ing. Ricardo Markiewicz
http://www.p39.com.ar/

**Comment by Gazer** [comment]
A pre-release version is now available on pub.dev. Please update the library to 0.2.0-dev.1 in your pubspec.yaml and report if that solves the problem.

**Comment by Gazer** [comment]
0.2.0-dev.2 released

**Comment by Gazer** [comment]
If no other feedback is provided, I will release 0.2.0 tomorrow. Thanks all for the feedback

**Comment by tonycesar** [comment]
> If no other feedback is provided, I will release 0.2.0 tomorrow. Thanks all for the feedback

@Gazer  I get the error with  com.mercadopago.android.px:services, 4.53.1 using 0.2.0-dev.2 

![image](https://user-images.githubusercontent.com/4418717/197892455-37e6d7a0-0c0b-4507-9fc5-ae7eba727390.png)

**Comment by Gazer** [comment]
Getting closed, 0.2.0-dev.3. was released. Hopefully this is the last dev release

**Comment by jpcodr** [comment]
Hola @Gazer

He recibido el mismo error que el post original aún usando la version `0.2.0-dev.3`:

<img width="693" alt="Screenshot 2023-02-13 at 18 27 35" src="https://user-images.githubusercontent.com/3935083/218607767-69de68d3-5ae6-47b8-b88c-bee49b39d5d4.png">

¿Necesito realizar algún paso extra?

Saludos

**Comment by Gazer** [comment]
Proba con la 0.2.0-dev.4, la dev2 no forzaba a la ultima versión entonces en algunas apps la dependencia no se actualizaba.
