### ISSUE TITLE
Unhandled Exception: PlatformException(0, Not ready, null)

### ISSUE THREAD

**Issue by javierhinmel** [Gazer/px-flutter#6]
Hi Ricardo, when I call the method 
`await MercadoPagoMobileCheckout.startCheckout(payment.publicKey, payment.preferenceId);`
from my widget, throws this exception

![image](https://user-images.githubusercontent.com/60926533/83986306-b20e2b80-a912-11ea-92f4-1e87f5214ca7.png)

I´m using Flutter v1.17.3

I would appreciate any ideas.
Thanks

**Comment by Gazer** [comment]
Hi, which version of the plugin are you using?

Also, could you attach the `adb logcat` output?

**Comment by javierhinmel** [comment]
Hi! I'm using the last version of plugin (0.0.2)
Here, the logcat output:

`2020-06-08 10:19:58.266 32123-32147/com.test.demo E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(0, Not ready, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
    #4      MercadoPagoMobileCheckout.startCheckout (package:mercado_pago_mobile_checkout/mercado_pago_mobile_checkout.dart:36:50)
    #5      __ReportPageState._enviarPedido (package:test/reporte_de_pedido_page.dart:200:54)
    <asynchronous suspension>
    #6      __ReportPageState.build.<anonymous closure>.<anonymous closure> (package:test/reporte_de_pedido_page.dart:182:33)
    #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
    #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
    #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
    #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
    #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
    #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
    #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
    #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
    #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
    #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
    #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
    #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
    #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #24     _rootRunUnary (dart:async/zone.dart:1196:13)
    #25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #27     _invoke1 (dart:ui/hooks.dart:275:10)
    #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)deli`

**Comment by Gazer** [comment]
Those are the only logs you get from the output of the `adb logcat` command? You can redirect the full output from the command line using `adb logcat > error.log` and then running your app, which will save a lot of debugging information that may help to find why your activity is not ready when you want to do a payment.

What you sent are only the Flutter errors but I need to check some logs that the plugin send to the logcat.

**Comment by javierhinmel** [comment]
Perdón Ricardo, cambio a modo "español", ya que sino estoy muy limitado. Corrí adb Logcat > errorLog.log y te envío eso. No veo que sea muy distinto a lo que ya te he pasado en el anterior mensaje. He probado tanto en un dispositivo fisico, como en un emulador y tengo el mismo problema. Parece que no se hace el binding del Activity que levanta las pantallas de mp.
Cualquier otra cosa que te sirva estoy a disposición.
Mil gracias.

[errorlog.log](https://github.com/Gazer/px-flutter/files/4747951/errorlog.log)

**Comment by Gazer** [comment]
Perdon, no me hice entender, necesito los logs desde que arranca la aplicacion hasta que aparece el error, no solo desde que apretas el boton hasta el error. Lo que quiero ver es si en algun momento se conecta/desconecta el plugin de la activity ya que tengo logs en esos callbacks del plugin.

En que version de android estas ejecutando la app? Asi trato de reproducir usando la misma version.

**Comment by javierhinmel** [comment]
Ok, ahora genero los logs desde el inicio. Ahora estoy probando con un emulador Api level 24. También probé con mi dispositivo que tiene Android 9.

**Comment by javierhinmel** [comment]
Ricardo, te paso el log desde que arranca la app.
Por otro lado, he creado la app de "ejemplo" que hiciste para el plugin y, si bien, para correrlo en android 7 en adelante tuve que agregarle en el manifest `android:usesCleartextTraffic="true"` (ya que mercado pago llama a url con protocolo https), dicho ejemplo funcionó correctamente. 
En mi App sigue sin funcionar. Agregué la llamada que haces al plugin para obtener la platformVersion, para verificar si no era problema de que el plugin necesita estar llamado desde el initState, pero al parecer no viene por allí el problema.

Aquí va el log.
[dumplog3.log](https://github.com/Gazer/px-flutter/files/4748848/dumplog3.log)

**Comment by Gazer** [comment]
Es muy raro, en el log aparece el `MercadoPagoPlugin: Starting checkout for ..` pero no aparece nunca el `MercadoPagoPlugin: onActivityResult`, como que no se llega a inicializar el plugin a tiempo. Voy a ver si puedo reproducirlo en alguna app de ejemplo.

**Comment by Gazer** [comment]
```                            Process ar.com.p39.yotellevoapp created for activity {ar.com.p39.yotellevoapp/ar.com.p39.yotellevoapp.MainAct
                            ivity}
                            PID: 17425   UID:    GIDs:

         39.yotellevoap  I  Not late-enabling -Xcheck:jni (already on)
                         E  Unknown bits set in runtime_flags: 0x8000
                         W  Unexpected CPU variant for X86 using defaults: x86
         DynamiteModule  W  Local module descriptor class for com.google.firebase.auth not found.
           FirebaseAuth  D  Notifying id token listeners about user ( IsiMYE0ocGewzNVUEEaf5i3xvD02 ).
   FirebaseInitProvider  I  FirebaseApp initialization successful
      ResourceExtractor  I  Found extracted resources res_timestamp-1-1591705992672
                         I  Resource version mismatch res_timestamp-1-1591706245867
         39.yotellevoap  W  Verification of boolean com.google.android.gms.measurement.internal.zzah.zzj() took 162.348ms
                 libEGL  D  Emulator has host GPU support, qemu.gles is set to 1.
                   libc  W  Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
         39.yotellevoap  W  Verification of void com.google.android.gms.measurement.internal.zzis.<init>(com.google.android.gms.measuremen
                            t.internal.zzgf) took 120.556ms
           RenderThread  W  type=1400 audit(0.0:104): avc: denied { write } for name="property_service" dev="tmpfs" ino=7420 scontext=u:r:
                            untrusted_app_27:s0:c134,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 a
                            pp=ar.com.p39.yotellevoapp
                 libEGL  D  loaded /vendor/lib/egl/libEGL_emulation.so
                         D  loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
                         D  loaded /vendor/lib/egl/libGLESv2_emulation.so
         39.yotellevoap  W  Verification of void com.google.android.gms.measurement.internal.zzis.zzae() took 163.844ms
                         W  Verification of void com.google.android.gms.common.internal.BaseGmsClient.zza(int, android.os.IInterface) took
                             230.760ms
         DynamiteModule  W  Local module descriptor class for com.google.firebase.auth not found.
           FirebaseAuth  I  [FirebaseAuth:] Loading module via FirebaseOptions.
                         I  [FirebaseAuth:] Preparing to create service connection to gms implementation
                     FA  I  App measurement initialized, version: 21028
                         I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
                         I  To enable faster debug mode event logging run:
                         I    adb shell setprop debug.firebase.analytics.app ar.com.p39.yotellevoapp
      ResourceExtractor  I  Extracted baseline resource assets/flutter_assets/kernel_blob.bin
                         I  Extracted baseline resource assets/flutter_assets/vm_snapshot_data
                         I  Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
         HostConnection  D  HostConnection::get() New Host Connection established 0xd5b82b80, tid 17425
                         D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDRO
                            ID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_ho
                            st_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_
                            vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
          EGL_emulation  D  eglCreateContext: 0xe11114e0: maj 3 min 0 rcv 3
         HostConnection  D  HostConnection::get() New Host Connection established 0xd903f820, tid 17473
                         D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDRO
                            ID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_ho
                            st_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_
                            vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
          EGL_emulation  D  eglMakeCurrent: 0xe11114e0: ver 3 0 (tinfo 0xd900f980)
      MercadoPagoPlugin  D  onAttachedToActivity```

ahi lo integre en una app que tengo y funciona bien, se llama al onAttached y despues el startCheckout inicia sin problemas. Fijate si podes aislar un ejemplo que falle desde tu codigo y subirlo a algun lado al que pueda tener acceso y revisar.

**Comment by javierhinmel** [comment]
Ok, me fijo. Hace falta llamar al plugin en initState para darle tiempo a inicializar o directamente al momento de usuarlo es suficiente?

**Comment by Gazer** [comment]
No, en teoría el plugin se inicializa cuando arranca la app, así que cuando
ves la primera pantalla dibujada ya debería estar inicializado.

Lo que no se es por qué en tu caso no se están ejecutando los callbacks.

Fíjate en la carpeta android/ de tu proyecto y  busca la MainActivity
(puede ser .java o .kt según si configuraste kotlin o no) y pegame el
código de esa clase. Quizás esta usando la forma vieja de inicializar
plugins.

**Comment by javierhinmel** [comment]
Te paso la Application y MainActivity:

```
public class App extends FlutterApplication implements
        PluginRegistrantCallback {

    @Override
    public void onCreate() {
        super.onCreate();
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

```
public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    FlutterMain.startInitialization(this); //Added line
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```

**Comment by Gazer** [comment]
Mi MainActivity luce como esto:
```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

ese FlutterMain lo agregaste vos?, quizas reemplazar el onCreate con la sobreescritura de configureFlutterEngine (ojo que en mi caso es Kotlin y el tuyo Java).

**Comment by javierhinmel** [comment]
No, estaba así. El proyecto tiene varios meses. Es probable que, como bien decís, haya cambiado la forma de registrar. Voy a probar hacer es cambio y te aviso.
Gracias

**Comment by Gazer** [comment]
Efectivamente si la app fue creada con una versión anterior a la 1.12 hay que actualizar el MainActivity, acá hay una guía oficial: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by javierhinmel** [comment]
Eureka! Era eso. Actualicé el source de Android y ahora funciona.
Mil gracias @Gazer  por el soporte!
PD. Ya me suscribí a tu canal de YT :)
