### ISSUE TITLE
Cast error

### ISSUE THREAD

**Issue by Holyblade** [Gazer/px-flutter#60]
Hi,

while compiling my code for test found a cast error on line 18 at json['installments'] as String?, [payment_result.g.dart](https://github.com/Gazer/px-flutter/blob/master/lib/src/payment_result.g.dart) - "_CastError (type 'int' is not a subtype of type 'String?' in type cast)." Probably it must be some new modification on mercado pago, because 2 weeks ago I didn't had this error.

I changed it to "json['installments'].toString() as String?" and works perfect for me at least.

I attached a print bellow if you wanna check.

![Error](https://user-images.githubusercontent.com/61342224/216784209-fdb592f8-66d8-4d36-b34f-c333692373e0.PNG)

Thanks for your efforts in bringing this lib ready for us.

**Comment by tallesdantas** [comment]
same problem here

**Comment by Gazer** [comment]
Hi, should be fixed in 0.2.0-dev4
