### ISSUE TITLE
Hola, vi tu video me gusto

### ISSUE THREAD

**Issue by CarlosTaborda** [Gazer/px-flutter#8]
estoy intentando seguir tu tutorial pero a la hora de pagar me aparece una pequeña alerta pero esta vaciá, he mirado el logcat pero no me aparece nada extraño, me gustaria saber como imprimr los errores de android nativo https://pasteboard.co/JnUgRbM.png

**Comment by Gazer** [comment]
Lo que te agrega es lo que esta en rojo? No termino de entender.

**Comment by CarlosTaborda** [comment]
Hola al realizar el pago, no lo permitía salia esa pequeña ventana, mire el log pero no salía nada extraño, pero ahora que veo el layout se dañaba completamente, no se veian las imagenes de tarjeta de credito etc. Lamento no poder darte información necesitabamos hacer la integración rapidamente y optamos por otra pasarela.

**Comment by quesad300** [comment]
Carlos Taborda hola, tengo el mismo problema pudiste solucionarlo? aquí pongo el error 
![problemas mercado pago](https://user-images.githubusercontent.com/33933526/93929234-2c579580-fce1-11ea-993c-bc89444d0c0b.jpg)

**Comment by quesad300** [comment]
CarlosTaborda que otra pasarela ocupaste? igual necesito realizar esta integración lo antes posible

**Comment by CarlosTaborda** [comment]
> 
> 
> CarlosTaborda que otra pasarela ocupaste? igual necesito realizar esta integración lo antes posible

No lo pude usar, usé  una pasarela que se llama payvalida, es de colombia, no sé si esta disponible en otrs paises

**Comment by quesad300** [comment]
voy a revisarla muchas gracias, igual tampoco logre ubicar los logs de error para hacer la corrección.

**Comment by Gazer** [comment]
Por lo que dicen en [este](https://github.com/Gazer/px-flutter/issues/10#issuecomment-740266622) otro ticket ese cartel rojo sale cuando usas el email del merchant como el email del que está pagando. No podés pagarte a vos mismo.
