### ISSUE TITLE
Min iOS version

### ISSUE THREAD

**Issue by DiegoLovera** [Gazer/px-flutter#9]
Hola, he iniciado un desarrollo y estoy haciendo uso de tu extensión, en android no hay ningún problema pero en iOS sí. 

La documentación creo que difiere con lo que tienes en el ejemplo de implementación de iOS, en la clase `AppDelefate.swift` del ejemplo hay 1 linea más que en la documentación y el error con el que me tope es que al iniciar un proyecto de 0 con flutter el mínimo de versión de iOS se configura en 8, intente correr la app y el único error que era mostrado es `flutter error running pod install`, así que me metí al ejemplo a ver si podía encontrar la diferencia y efectivamente note que en tu proyecto de ejemplo el mínimo esta configurado como 10, hice la modificación y funcionó sin problema, sugiero que agregues este detalle a la documentación para iOS en caso de ser esto cierto.

**Comment by Gazer** [comment]
Hola, gracias por analizar esto, definitivamente iOS no es mi fuerte y puede que algo no este bien, voy a revisar bien para que quede la min version de ios en lo mas bajo que permita el SDK de Mercado Pago. Si tenes ya algo y queres enviar el PR bienvenido tambien!

**Comment by vicenteign** [comment]
Hola! Tengo el mismo problema que @DiegoLovera. ¿Dónde puedo modificar la version de IOS para que corra en 10?

**Comment by DiegoLovera** [comment]
@vicenteign Yo hice 2 modificaciones, probablemente fueron lo mismo pero no soy un iOS developer y desconozco un poco:
En el archivo "Podfile" dentro de ios > Podfile, esta la segunda linea comentada y dice lo siguiente `# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
` simplemente removi el comentario y lo modifique de 8 a 10.0 y por si acaso abrí el proyecto con xCode y modifique las opciones del archivo Runner `iOS Deployment Target` a 10 también.

**Comment by vicenteign** [comment]
Muchas gracias, funcionó con esas dos modificaciones  👍🏻
